from enum import Enum

class Regelarten(Enum):
    KLEINERALS = "KLEINERALS"
    KLEINERGLEICHALS = "KLEINERGLEICHALS"
    ISTGLEICH = "ISTGLEICH"
    GROESSERALS = "GROESSERALS"
    GROESSERGLEICHALS = "GROESSERGLEICHALS"